### PR TITLE
7903214: JOL: Complete some TODOs in VMOptions

### PR DESCRIPTION
**Pull request by SteafanMrZhou**
I'm sorry about the last commit, I forgot to update my branch.
I have updated the branch synchronously, please check the PR,thanks a lot.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Change must be properly reviewed (1 review required, with at least 1 [Committer](https://openjdk.org/bylaws#committer))

### Issue
 * [CODETOOLS-7903214](https://bugs.openjdk.org/browse/CODETOOLS-7903214): JOL: Complete some TODOs in VMOptions

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jol pull/29/head:pull/29` \
`$ git checkout pull/29`

Update a local copy of the PR: \
`$ git checkout pull/29` \
`$ git pull https://git.openjdk.org/jol pull/29/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 29`

View PR using the GUI difftool: \
`$ git pr show -t 29`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jol/pull/29.diff">https://git.openjdk.org/jol/pull/29.diff</a>

</details>

### CODE REVIEW

**Comment by shipilev** [comment]
Can you also please go to https://github.com/SteafanMrZhou/jol/actions/ -- and check that workflows are enabled? The PRs need to be tested, and workflows are supposed to run automatically.

**Comment by SteafanMrZhou** [comment]
> Can you also please go to https://github.com/SteafanMrZhou/jol/actions/ -- and check that workflows are enabled? The PRs need to be tested, and workflows are supposed to run automatically.

The tested has completed,thanks.

**Review by shipilev — CHANGES_REQUESTED** [review]
Ah, now I remember why these are not printed. On 32-bit VMs, where the options are not available, it would print unnecessary noise:

```
# WARNING: Unable to get compressed oops. java.lang.IllegalArgumentException: VM option "UseCompressedOops" does not exist
# WARNING: Unable to get compressed class pointersjava.lang.IllegalArgumentException: VM option "UseCompressedClassPointers" does not exist
# WARNING: Unable to get compressed oops. java.lang.IllegalArgumentException: VM option "UseCompressedOops" does not exist
# WARNING: the compressed oops is unavailable
# Running 32-bit HotSpot VM.
# Objects are 8 bytes aligned.
#                       ref, bool, byte, char, shrt,  int,  flt,  lng,  dbl
# Field sizes:            4,    1,    1,    2,    2,    4,    4,    8,    8
# Array element sizes:    4,    1,    1,    2,    2,    4,    4,    8,    8
# Array base offsets:    12,   12,   12,   12,   12,   12,   12,   16,   16

...
```

These warnings cannot be reasonably fixed by users, so there is no point in printing them.

I suggest we just drop the `// TODO:` lines in this patch, and move on.

**Comment by SteafanMrZhou** [comment]
Alright,I changed for a later.just wait a minute.

**Review by shipilev — APPROVED** [review]

**Comment by SteafanMrZhou** [comment]
Why can't PRs be merged, but integrated?

**Comment by shipilev** [comment]
Bots are handling all integrations to perform checks, do proper metadata updates, etc. This is how OpenJDK infra works.

**Comment by SteafanMrZhou** [comment]
How to become a committer of this project?Thanks a lot.

**Comment by shipilev** [comment]
> How to become a Committer of this project?

The same way as for the rest of OpenJDK and other OSS projects: accrue a track record of good contributions, reviews, involvement.

**Pull request closed without merging**
